# -*- coding: utf-8 -*-
from agentscope.agent import AgentBase, UserAgent
from agentscope.message import Msg
from .web_user_input import WebUserInput
from typing import Any
from games.diplomacy.web.game_state_manager import GameStateManager
from games.diplomacy.utils import Parser

class WebUserAgent(UserAgent):
    def __init__(
        self,
        name: str,
        state_manager: GameStateManager,
    ):
        """Initialize WebUserAgent.
        
        Args:
            name: Agent name
            state_manager: GameStateManager instance
        """
        super().__init__(name=name)
        self.state_manager = state_manager
        self.agent_id = self.id
        
        # Override input method to use WebUserInput
        web_input = WebUserInput(state_manager)
        self.override_instance_input_method(web_input)

    async def observe(self, x: dict) -> None:
        await super().observe(x)
        
        if self.state_manager.mode == "participate":
            if isinstance(x, Msg):
                content = x.content
                sender = x.name
            else:
                content = str(x)
                sender = "System"
            
            log_entry = f"{content}"
            if hasattr(self.state_manager, 'update_game_state'):
                self.state_manager.update_game_state(logs=log_entry) #added mxj

    async def reply(
        self,
        msg: Msg | list[Msg] | None = None,
        structured_model: Any = None,
    ) -> Msg:
        """Receive input message(s) and generate a reply message from the user.
        
        Args:
            msg: The message(s) to be replied. If not None, observe them first.
            structured_model: Optional structured model for structured input.
            
        Returns:
            The reply message generated by the user.
        """
        # Observe the incoming message(s) first
        if msg is not None:
            await self.observe(msg)
        
        # Call parent reply to get user input
        return await super().reply(msg=msg, structured_model=structured_model)


class ObserveAgent(AgentBase):
    def __init__(self, name: str, state_manager, **kwargs):
        super().__init__(**kwargs)
        self.name = name
        self.state_manager = state_manager

    async def observe(self, x: dict) -> None:
        # added mxj
        if isinstance(x, Msg):
            content = x.content
            sender = x.name
        else:
            content = str(x)
            sender = "Unknown"

        log_entry = f"[{sender}] {content}"
        if hasattr(self.state_manager, 'update_game_state'):
            self.state_manager.update_game_state(obs_log_entry=log_entry)

    def reply(self, x: dict = None) -> Msg:
        return Msg(self.name, content="", role="assistant")
